# Generated by Django 6.0 on 2025-12-25 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='대회 ID (Codeforces)')),
                ('name', models.CharField(max_length=100, verbose_name='대회명')),
                ('start_time', models.DateTimeField(verbose_name='대회 시작시간')),
                ('end_time', models.DateTimeField(verbose_name='대회 종료시간')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_status', models.CharField(default='', max_length=100, verbose_name='문제 풀이 현황')),
                ('total_score', models.FloatField(default=0, verbose_name='총점')),
                ('penalty', models.IntegerField(default=0, verbose_name='패널티(소요시간)')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest', verbose_name='참가 대회')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='참가자')),
            ],
            options={
                'verbose_name': '대회 참가자',
                'verbose_name_plural': '대회 참가자들',
                'ordering': ['-total_score', 'penalty'],
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, verbose_name='문제 번호')),
                ('points', models.FloatField(default=0, verbose_name='배점')),
                ('rating', models.IntegerField(default=0, verbose_name='난이도')),
                ('description_kr', models.TextField(blank=True, verbose_name='문제 설명')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest', verbose_name='관련 대회')),
            ],
            options={
                'verbose_name': '대회 문제',
                'verbose_name_plural': '대회 문제들',
                'unique_together': {('contest', 'index')},
            },
        ),
    ]
