# Generated by Django 6.0 on 2025-12-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': '대회', 'verbose_name_plural': '대회'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-total_score', 'penalty'], 'verbose_name': '대회 참가자', 'verbose_name_plural': '대회 참가자'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '대회 문제', 'verbose_name_plural': '대회 문제'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='penalty',
            field=models.IntegerField(default=0, verbose_name='패널티'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_contests', to=settings.AUTH_USER_MODEL, verbose_name='참가자'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contest.contest', verbose_name='관련 대회'),
        ),
    ]
