# Generated by Django 6.0 on 2025-12-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='url',
            field=models.URLField(blank=True, verbose_name='문제 링크'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contest.contest', verbose_name='참가 대회'),
        ),
    ]
