# Generated by Django 5.2.9 on 2025-12-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_participant_contest'),
        ('contest', '0003_problem_url_alter_participant_contest'),
    ]

    operations = [
    ]
