# Generated by Django 5.2.9 on 2026-01-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_contest_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_rating_applied',
            field=models.BooleanField(default=False, verbose_name='레이팅 반영 여부'),
        ),
    ]
