# Generated by Django 5.2.9 on 2026-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_is_rating_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='문제명'),
            preserve_default=False,
        ),
    ]
