# Generated by Django 5.2.9 on 2026-02-01 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='virtual_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='가상 ID'),
        ),
    ]
