# Generated by Django 5.2.9 on 2026-02-08 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_contest_virtual_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='변동 후 Rating')),
                ('rating_change', models.IntegerField(verbose_name='Rating 변동량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='contest.contest', verbose_name='관련 대회')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '레이팅 변동 기록',
                'verbose_name_plural': '레이팅 변동 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
