# Generated by Django 5.2.9 on 2026-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_ratinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='freeze_minutes',
            field=models.IntegerField(default=30, verbose_name='프리즈 시간(분)'),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='프리즈 상태'),
        ),
        migrations.AddField(
            model_name='participant',
            name='frozen_penalty',
            field=models.IntegerField(default=0, verbose_name='프리즈 시점 패널티'),
        ),
        migrations.AddField(
            model_name='participant',
            name='frozen_problem_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='프리즈 시점 풀이 현황'),
        ),
        migrations.AddField(
            model_name='participant',
            name='frozen_total_score',
            field=models.FloatField(default=0, verbose_name='프리즈 시점 총점'),
        ),
    ]
