# Generated by Django 5.2.9 on 2026-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_scoreboard_freeze_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allow_freeze',
            field=models.BooleanField(default=True, verbose_name='프리즈 허용 여부'),
        ),
    ]
