# Generated by Django 5.2.9 on 2026-03-27 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_allow_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='editorial_pdf',
            field=models.FileField(blank=True, null=True, upload_to='editorials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='해설 PDF'),
        ),
    ]
