# Generated by Django 5.2.9 on 2025-12-26 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="학교"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="학과"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="학번",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="이름"
                    ),
                ),
                (
                    "codeforces_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Codeforces ID",
                    ),
                ),
                (
                    "elo_rating",
                    models.IntegerField(
                        default=1500,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="ELO Rating",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
                "ordering": ["-elo_rating", "-created_at"],
            },
        ),
    ]
