# Generated by Django 5.2.9 on 2026-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=100, verbose_name='학과'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='elo_rating',
            field=models.IntegerField(default=1500, verbose_name='ELO Rating'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='real_name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=100, verbose_name='학교'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='학번'),
        ),
    ]
