# Generated by Django 5.2.9 on 2026-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_department_alter_profile_elo_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='학번')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '가입 허용 리스트',
                'verbose_name_plural': '가입 허용 리스트',
                'ordering': ['-created_at'],
            },
        ),
    ]
