# Generated by Django 5.2.9 on 2026-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='가입 여부'),
        ),
    ]
